# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
---
ci:
  autoupdate_schedule: quarterly
  skip: ["identity", "uv-lock"]

exclude: .*/(input|sample).*\.data

repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        name: Don't allow commits to the main branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Ensure files end with a newline character
      - id: mixed-line-ending
        name: Align mixed line ending
      - id: check-added-large-files
        name: Check for large files
      - id: check-json
        name: Check JSON files are valid and parseable
      - id: check-yaml
        name: Check YAML files are valid and parseable
      - id: check-toml
        name: Check TOML files are valid and parseable
      - id: check-ast
        name: Validate Python
      - id: detect-private-key
        name: Check for the existence of private keys

  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
      - id: check-pre-commit-ci-config
        name: Validate pre-commit CI config

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.8.22
    hooks:
      - id: uv-lock
        name: Check that the lock file is up-to-date

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff-check
        name: Lint Python code
        args: ["--fix"]
        exclude: "advent_of_code/meta/template/main.py"
      - id: ruff-format
        name: Format Python code
        exclude: "advent_of_code/meta/template/main.py"

  - repo: https://github.com/billwallis/bills-hooks
    rev: v0.0.6
    hooks:
      - id: tidy-gitkeep
        name: Remove redundant .gitkeep files
